### ISSUE TITLE
Add documentation on how to set up databases properly

### ISSUE THREAD

**Issue by Nuc1eoN** [pterodactyl/documentation#108]
The documentation covers pretty much most of the required setup for the pterodactyl panel. However it is still missing a basic guidance/best practice how to set up the database backend for creating database hosts and databases. Even though those database functions are available in the GUI, there is no documentation on how to make them work in the background.

If somebody has had no or little experience with mysql this can be very daunting. Especially from a security perspective I guess one could do many things wrong, like opening ports to the whole www, assigning to wrong permissions to mysql users and so on. Also I think the installation of pterodactyl is simply incomplete without setting this up.

I would do this myself but I don't think I have sufficient understanding for this.

**Comment by parkervcp** [comment]
It's not our job to teach people how to secure their database. We only documented what to install and how to do a basic configuration to get the panel running.

**Comment by DomiiBunn** [comment]
#127 Feel like this can be closed?

**Comment by lancepioch** [comment]
Closed because of #127
