### ISSUE TITLE
Private registry auth requires an images array to work

### ISSUE THREAD

**Issue by TrixterTheTux** [pterodactyl/documentation#113]
The section at https://pterodactyl.io/daemon/configuration.html#private-registries should also document the usage of the ``images`` array required for the authentication config to be used.

Relevant lines from the daemon: https://github.com/pterodactyl/daemon/blob/v0.6.12/src/helpers/image.js#L75-L85

**Comment by Yomanz** [comment]
i just did this without realising there was an issue

https://github.com/pterodactyl/documentation/pull/140
