### ISSUE TITLE
New setups frequently encounter MySQL permission errors because 127.0.0.1 != localhost

### ISSUE THREAD

**Issue by iamkubi** [pterodactyl/documentation#123]
I've seen this issue frequently in support channels, and I think that at least under setup conditions users are running into MySQL permission issues because of conflicts in the setup instructions.

MySQL grants are instructed to be set at https://pterodactyl.io/tutorials/mysql_setup.html#creating-a-user as:
`CREATE USER 'pterodactyl'@'127.0.0.1' IDENTIFIED BY 'somePassword';`

It's common for users to show up with this error in their logs:
[2019-08-27 17:31:36] production.ERROR: QueryException: SQLSTATE[HY000] [1698] Access denied for user 'pterodactyl'@'localhost' (SQL: select * from information_schema.tables where table_schema = panel and table_name = migrations) in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664

I believe this is because 'pterodactyl'@'127.0.0.1' is not equivalent to 'pterodactyl'@'localhost'.  I think this can be resolved with documentation once I better understand the set of instructions people follow to end up in this situation.

**Comment by DaneEveritt** [comment]
This isn't a docs issue, he used `localhost` when the installer has a bright orange warning not to use it.

Also sounds like he cached his configuration, which is why it wasn't changing when you changed the environment file.

**Comment by xoorath** [comment]
I don't think the conclusion here is right @DaneEveritt . I haven't typed `localhost` once and am getting the same issue.

I've just been pasting from the guide and replacing only what I've been instructed to / what was obvious such as passwords.

I think there might be some niche configuration problem going on. Do you think that's possible? Obviously could still be user error, but I have no idea how to fix this as I'm not seeing localhost appear anywhere (such as my env file).

**Comment by nldoty** [comment]
I went back through the [Setting up MySQL](https://pterodactyl.io/tutorials/mysql_setup.html) guide and any time it said to use `'pterodactyl'@'`127.0.0.1'` I changed it to `'pterodactyl'@'localhost'` and that resolved my issues. There's definitely something wonky going on in the setup.

**Comment by StarGamerShalom** [comment]
I just got the same thing in trying to install pterodactyl panel right now. I followed the current copy paste info too changing only what prompted to change and never typed in localhost.  I am running a VPS server from a hosting company with ubuntu 24.04 and Sql 8.0 
![sqlerror](https://github.com/user-attachments/assets/05b26603-c9cc-448b-a64f-239e00524802)
