### ISSUE TITLE
GITHUB_TOKEN has bugs

### ISSUE THREAD

**Issue by peaceiris** [pterodactyl/documentation#142]
https://github.com/pterodactyl/documentation/blob/0d0da96c9de16aa305b703ba7599e0a20b742180/.github/workflows/github-pages.yml#L20

Check https://github.com/pterodactyl/documentation/commits/gh-pages, you find that GitHub Pages build event did not start.

Please do not use `GITHUB_TOKEN`, use `ACTIONS_DEPLOY_KEY` or `PERSONAL_TOKEN`

cf. https://github.com/peaceiris/actions-gh-pages/issues/9

**Comment by schrej** [comment]
I think in this case it was because I messed up the `if: ` statement for the deploy step. After we fixed that, it started to deploy.
https://github.com/pterodactyl/documentation/commit/0d0da96c9de16aa305b703ba7599e0a20b742180/checks

**Comment by peaceiris** [comment]
Check https://github.com/pterodactyl/documentation/commits/gh-pages

<img width="502" alt="Screen Shot 2019-09-25 at 6 59 46" src="https://user-images.githubusercontent.com/30958501/65553575-20b48000-df62-11e9-9dd0-3cb314397d91.png">

**Comment by DaneEveritt** [comment]
Yes, I'm unsure what you're saying the issue is here? It appears to have deployed without a problem?

**Comment by peaceiris** [comment]
There is no checkmark. We cannot access the event log of this commit. This means that GitHub Pages build event did not start.

![github](https://user-images.githubusercontent.com/30958501/65564952-77818000-df89-11e9-9d97-8532edba69db.jpg)

See this log: https://github.com/pterodactyl/documentation/deployments

You can find the latest event "2 days ago".

<img width="644" alt="Screen Shot 2019-09-25 at 11 46 57" src="https://user-images.githubusercontent.com/30958501/65565223-405f9e80-df8a-11e9-9c3b-cebfa7e9fbff.png">

**Comment by peaceiris** [comment]
LGTM. Thank you.
