### ISSUE TITLE
Active: failed (Result: start-limit)

### ISSUE THREAD

**Issue by RYHTN** [pterodactyl/documentation#155]
● pteroq.service - Pterodactyl Queue Worker
   Loaded: loaded (/etc/systemd/system/pteroq.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2019-10-28 17:23:19 UTC; 1s ago
  Process: 5069 ExecStart=/usr/bin/php /var/www/pterodactyl/artisan queue:work --queue=high,standard,low --sleep=3 --tries=3 (code=exited, status=217/USER)
 Main PID: 5069 (code=exited, status=217/USER)

Oct 28 17:23:19 720.my.cloudef.com systemd[1]: Unit pteroq.service entered failed state.
Oct 28 17:23:19 720.my.cloudef.com systemd[1]: pteroq.service failed.
Oct 28 17:23:19 720.my.cloudef.com systemd[1]: pteroq.service holdoff time over, scheduling restart.
Oct 28 17:23:19 720.my.cloudef.com systemd[1]: Stopped Pterodactyl Queue Worker.
Oct 28 17:23:19 720.my.cloudef.com systemd[1]: start request repeated too quickly for pteroq.service
Oct 28 17:23:19 720.my.cloudef.com systemd[1]: Failed to start Pterodactyl Queue Worker.
Oct 28 17:23:19 720.my.cloudef.com systemd[1]: Unit pteroq.service entered failed state.
Oct 28 17:23:19 720.my.cloudef.com systemd[1]: pteroq.service failed.

pls help

**Comment by Sir3lit** [comment]
This should be taken to the discord for support.
