### ISSUE TITLE
PHP 7.3 in 'Getting Started' guide

### ISSUE THREAD

**Issue by vilhelmprytz** [pterodactyl/documentation#158]
I noticed PHP 7.2 was listed as dependency on the official 'Getting Started' guide ([Getting Started](https://pterodactyl.io/panel/getting_started.html#dependencies)). Should this be replaced with PHP 7.3 instead as PHP 7.2 is soon reaching end of 'active support' (see [supported versions](https://www.php.net/supported-versions.php)).

Cheers

**Comment by Sir3lit** [comment]
Should be noted that security releases are supported until 30 Nov 2020

**Comment by ljavanbeek** [comment]
PHP 7.2 was already replaced by PHP 7.3 in some of the community guides (CentOS 7 and the Debian guides), it just seems logical to replace it everywhere on the docs, right?

**Comment by DaneEveritt** [comment]
It does, and likely will happen with the official 0.8 release since that is a great time to roll back through the documentation and get everything squared away. There is indeed nothing stopping people from using 7.3 though, and if someone would like to PR the necessary changes I'm happy to merge them early.

**Comment by VilhelmPrytz** [comment]
> It does, and likely will happen with the official 0.8 release since that is a great time to roll back through the documentation and get everything squared away. There is indeed nothing stopping people from using 7.3 though, and if someone would like to PR the necessary changes I'm happy to merge them early.

I have created a PR for this https://github.com/pterodactyl/documentation/pull/160

(also accidentally closed and reopened the issue)
