### ISSUE TITLE
PPA Repo issue for Certbot

### ISSUE THREAD

**Issue by ozzygit** [pterodactyl/documentation#164]
I wasn't sure to propose doco update or raise issue. The certbot PPA Repo doesn't work on Debian 9 stretch. Perhaps this should be somehow documented? Does it definitely work for Ubuntu?

**Comment by parkervcp** [comment]
The PPA format doesnt support Debian.

The docs specifically note that Ubuntu is the expected distro for install.

On a related note, this also exists. https://pterodactyl.io/community/installation-guides/daemon/debian9.html

**Comment by ozzygit** [comment]
Thanks for the feedback. I was tired and skimming over some of the info I think so obviously missed that!
