### ISSUE TITLE
I have a probleme

### ISSUE THREAD

**Issue by Ezermoz1** [pterodactyl/documentation#209]
ezermoz@*:/var/www/pterodactyl$ sudo systemctl enable --now redis-server
Synchronizing state of redis-server.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable redis-server
ezermoz@*:/var/www/pterodactyl$ sudo systemctl enable --now pteroq.service
Failed to execute operation: No such file or directory
ezermoz@i:/var/www/pterodactyl$

**Comment by parkervcp** [comment]
We ask that you take support issues to discord.

http://discord.gg/pterodactyl
