### ISSUE TITLE
Setup guide should have next page links

### ISSUE THREAD

**Issue by iamkubi** [pterodactyl/documentation#210]
https://pterodactyl.io/panel/0.7/getting_started.html

Someone in support said "I followed this page top to bottom" and still got the default NGINX page.  Sure enough, they had never created the webserver config, because nothing on that page told them to, and it did not include any links to the next steps directly on the page.

You can tell looking at the sidebar there are more docs, but there should be next page links to indicate to users that there are still additional steps required.

**Comment by VirtualHorror** [comment]
Any estimates on when this will be implemented?

**Comment by schrej** [comment]
There are no estimates regarding when something will be done.
