### ISSUE TITLE
List servers by user nowhere to be seen

### ISSUE THREAD

**Issue by imeuropa** [pterodactyl/documentation#228]
I can't find any "list servers by user" in the docs even though I've been told that it exists, does it exist or not? If so can the documentation be updated?

**Comment by parkervcp** [comment]
Admin see all servers on the panel. Users only see servers they own.

**Comment by imeuropa** [comment]
Oh sorry I didn't specify, I was referring to the API.

**Comment by parkervcp** [comment]
The API docs are not official and they have their own place to report issues.

https://dashflo.net/docs/api/pterodactyl/v0.7/#introduction

**Comment by imeuropa** [comment]
> The API docs are not official and they have their own place to report issues.
> 
> https://dashflo.net/docs/api/pterodactyl/v0.7/#introduction

Are there no official API docs?

**Comment by parkervcp** [comment]
There are currently no official api docs.

**Comment by LeCodeCo** [comment]
I believe you can get servers that you're a subuser of from the API with `?include=subusers`, or something along those lines.
