### ISSUE TITLE
"tar --strip-components=1 -xzvf panel.tar.gz" not working as intended Panel 1.0, beta 6

### ISSUE THREAD

**Issue by kruthers** [pterodactyl/documentation#238]
with beta 6 the command `tar --strip-components=1 -xzvf panel.tar.gz` when decompressing the panel zip to install it does not extra the right files and stops you from being able to run the following commands removing `--strip-components=1` fixes this and allows the right files to be accessed afterwards.

**Comment by schrej** [comment]
Shouldn't that be removed by #237 already?

**Comment by Sir3lit** [comment]
The command was updated in the upgrade guide. I didn't change it in the install guide.

**Comment by schrej** [comment]
resolved by #237 and #239
