### ISSUE TITLE
SSL Configuration with a random config file?

### ISSUE THREAD

**Issue by RamonRobben** [pterodactyl/documentation#240]
What do I do after I have generated SSL with certbot / nginx? Your instruction only shows some config file with the header SSL Configuration but it doesn't tell you if it's an example or where you can find your config or if you need to edit your config and where it could be located. Do I just ignore the random config?

I eventually just copied the config and pasted it in my /etc/nginx/nginx.conf and edited the higlighted parts but I am unsure if this is how I should have used the config .

This is the part I am completely confused about I think it could use some edits to make it more clear why there's a random ssl config.
https://pterodactyl.io/community/installation-guides/panel/ubuntu2004.html#ssl-configuration

**Comment by parkervcp** [comment]
Community guides are supplemental to the main guide

![image](https://user-images.githubusercontent.com/1207679/88343099-9ae29c00-cd0e-11ea-84e3-f138f0135e17.png)

**Comment by RamonRobben** [comment]
@parkervcp where did you find that guide if I may ask because I can't seem to find it. I just went to the website clicked on Ubuntu 20.04 and followed along xD

**Comment by parkervcp** [comment]
https://pterodactyl.io/panel/0.7/webserver_configuration.html

The standard guide
