### ISSUE TITLE
Swiping right shows the sidebar while on mobile

### ISSUE THREAD

**Issue by EgoMaw** [pterodactyl/documentation#243]
Every time you want to swipe right (for example while reading a code block), the side bar will pop up which makes it annoying and forces you to dismiss the side bar and continue reading through the docs.
I have no idea if this can be reproduced in iOS since I have an android phone, but it would be beneficial if this function could be disabled.

**Comment by TekExplorer** [comment]
code blocks, and similar assets that need horizontal scroll, have their own scroll bars. swipe inside the block or table itself and it wont impact the sidebar.

**Comment by AndyIsHereBoi** [comment]
This does not appear to be happening for me. Can anyone else confirm?

https://user-images.githubusercontent.com/69745145/172538376-f78644af-2ed6-48fc-9245-a2921778020c.mp4
