### ISSUE TITLE
Access denied for user 'pterodactyl'@'localhost' 

### ISSUE THREAD

**Issue by CheesyBC** [pterodactyl/documentation#246]
Hey, from what I can see this is a fairly common issue, but I cannot create a user, and also when I ran "php artisan migrate --seed" I got this error. I could delete my VM and make another one, but that is kind of a pain since I am using Microsoft Azure, and it would be easier for me if I could just change my host, (since what I see, I'm not supposed to use localhost, and that is why this is happening).

**Comment by CheesyBC** [comment]
By the way, I am using Debian 10, a fresh install as I said on Microsoft Azure.

**Comment by CheesyBC** [comment]
oops, hit the wrong post button.

**Comment by pressstartearly** [comment]
That access denied error is saying it cannot access your MySQL database. Make sure you created the database user correctly with the correct password and permissions. Also, check to make sure you configured the panel to use the correct username and password.

**Comment by matthewpi** [comment]
Issues are for reporting bugs or problems, not issues with your configuration.  If you need assistance, ask in Discord.
