### ISSUE TITLE
MySQL Documentation Improvement 

### ISSUE THREAD

**Issue by X-Niter** [pterodactyl/documentation#249]
Improvement on https://pterodactyl.io/tutorials/mysql_setup.html#allowing-external-database-access

For Ubuntu 18.04, It has been founded that the "bind-address=" option does not exist in "my.cnf". 
To find the "bind-address=" option you go to 50-server.cnf.

A member of the Discord is who had this answer, I will share a link to that individual's answer/convo.
 https://discordapp.com/channels/122900397965705216/272796619592695808/730897830155124888

Hope it helps improve some of y'alls  Documentation. 👍

**Comment by dudeisbrendan03** [comment]
1. You should not edit `50-server.cnf`, this is poor practice.
You should instead modify my.cnf to have the section you wish to override.
2. This issue is stale and should be closed

**Comment by Software-Noob** [comment]
The correct practice is to use `my.cnf`file to overwrite configuration which the documentation currently does, with emphasis on how to locate it
