### ISSUE TITLE
Add system dependency upgrade to 0.7 to 1.0 migration guide

### ISSUE THREAD

**Issue by schrej** [pterodactyl/documentation#255]
Some system dependencies, like mariadb, might require upgrades for 1.0 to work.

**Comment by TekExplorer** [comment]
Placing some sources here in case I or someone else gets around to doing this.
https://mariadb.com/kb/en/upgrading/
https://pterodox.com/guides/update-php.html

**Comment by BlackQuard** [comment]
Pterodactyl
