### ISSUE TITLE
Migration/installation Documentation for CentOS to Pterodactyl 1.0

### ISSUE THREAD

**Issue by ablac** [pterodactyl/documentation#256]
For CentOS Installation might want to add a few things:

Uninstall Old versions of Docker.
sudo yum remove docker-ce docker-ce-cli containerd.io

Install new version of Containerd.io
yum install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm

Setup New Docker Repository
sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

Install new versions of Docker:
sudo yum install docker-ce docker-ce-cli

This solves the issue with Docker API being To New on CentOS preventing Wings from Starting

**Comment by gamer4life1** [comment]
hmm, it seems that the community guides have to be updated to 1.0 altogether
