### ISSUE TITLE
[Clarity] Where exactly is my.cnf supposed to be? 

### ISSUE THREAD

**Issue by TekExplorer** [pterodactyl/documentation#286]
https://pterodactyl.io/tutorials/mysql_setup.html#allowing-external-database-access

make clear where exactly those files are.

**Comment by Hydra2k** [comment]
the docs say mysql.conf.d/mysqld.cnf

**Comment by Software-Noob** [comment]
The file is at  `/etc/mysqld/my.cnf` or  `/etc/mysql/mariadb.conf.d/50-server.cnf` depending on the setup. The users should know their own system set up or google if they don't know, holding hands all the way regarding every little thing will make the documentation pretty bloatware

**Comment by matthewpi** [comment]
> The file is at `/etc/mysqld/my.cnf` or `/etc/mysql/mariadb.conf.d/50-server.cnf` depending on the setup. The users should know their own system set up or google if they don't know, holding hands all the way regarding every little thing will make the documentation pretty bloatware

Anything we don't provide in the documentation just gets asked in the help channels, so regardless of if it is in the docs or not, people will still ask and require hand holding.

**Comment by TekExplorer** [comment]
the reason i ask is because the docs reference filenames such as 50-server.cnf and my.cnf, and not at all how to find it.
im seriously annoyed at the inconsistency of mysql/mariadb regarding that :(

**Comment by TekExplorer** [comment]
#249 is related.

**Comment by TekExplorer** [comment]
Each of these commands should list valid my.cnf files in order
```bash
mysqladmin --help | grep -A 1 "^Default"
mysql --help | grep -A 1 "^Default"
mysqld --help --verbose  | grep -A 1 "^Default"
```
If I can get verification that it works, we can just have users pick the first file and put the bind-address in there or something

**Comment by DaneEveritt** [comment]
I'm not interested in maintaining guides teaching people how to do basic server administration. It is not difficult for someone to just Google these things.
