### ISSUE TITLE
I am not sure what you are trying to achieve here. It actually does not work from my testing so the changes you suggested makes no sense.

### ISSUE THREAD

**Issue by GoldTanzil** [pterodactyl/documentation#374]
I am not sure what you are trying to achieve here. It actually does not work from my testing so the changes you suggested makes no sense.

```
root@panel:/var/www/pterodactyl# tzzone -I | awk '{print $1}'
145.239.115.75
root@panel:/var/www/pterodactyl# tzzone -I | awk '{print $1}'
-bash: tzzone: command not found
```

_Originally posted by @JackW6809 in https://github.com/pterodactyl/documentation/issues/373#issuecomment-857593196_

**Comment by parkervcp** [comment]
1. I don't know why you opened an issue for this.
2. tzzone is not a package I know of.
