### ISSUE TITLE
Game supported

### ISSUE THREAD

**Issue by geds3169** [pterodactyl/documentation#400]
Hello, I could read in your git, that you are planning in 2017 the possibility of managing an arma 3 or DayZ server. When is he this day?

Regards

**Comment by hwalker928** [comment]
Wrong repo to open the issue on, but here's one of the games

https://github.com/parkervcp/eggs/blob/master/game_eggs/steamcmd_servers/arma/arma3

**Comment by geds3169** [comment]
Thank you for the reply

King regards,

Geds
 
Provenance : Courrier pour Windows 10

De : Harry W.
Envoyé le :samedi 28 août 2021 15:28
À : pterodactyl/documentation
Cc : SCHLOSSER Guilhem; Author
Objet :Re: [pterodactyl/documentation] Game supported (#400)

Wrong repo to open the issue on, but here's one of the games
https://github.com/parkervcp/eggs/blob/master/game_eggs/steamcmd_servers/arma/arma3
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
