### ISSUE TITLE
Suggested change

### ISSUE THREAD

**Issue by Ferks-FK** [pterodactyl/documentation#419]
### Explanation
In the panel tutorial, but specifically in the "Getting Started" tab, change the following information:

```
php artisan p:environment:setup
php artisan p:environment:database

# To use PHP's internal mail sending (not recommended), select "mail". To use a
# custom SMTP server, select "smtp".
php artisan p:environment:mail
```

To:

```
php artisan p:environment:setup
php artisan p:environment:database

# To use PHP's internal mail sending (not recommended), select "mail". To use a
# custom SMTP server, select "smtp".
# If you don't need mail sending right now, ignore this command.
php artisan p:environment:mail
```

### Why this change?

This will prevent people from running this command without even needing to send mail, and most importantly, it will prevent these kinds of problems in discord:

```
[2021-12-10 17:22:35] production.ERROR: Connection could not be established with host smtp.example.com :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known
```

**Comment by Software-Noob** [comment]
That error is harmless and skipping the step won't affect that, because the dotenv file contains [default example values.](https://github.com/pterodactyl/panel/blob/develop/.env.example#L22) That command allows overwriting those values.

**Comment by Ferks-FK** [comment]
> That error is harmless and skipping the step won't affect that, because the dotenv file contains [default example values.](https://github.com/pterodactyl/panel/blob/develop/.env.example#L22) That command allows overwriting those values.

Good, then can I close this?
