### ISSUE TITLE
What is an .env file and where is it?

### ISSUE THREAD

**Issue by CodeCrafter912** [pterodactyl/documentation#43]
Hi,
First of all: Thank you for that piece of software, it's great!!
I think you should mention what .env files are and where they are stored.
Regards,
Dorian

**Comment by Lunaversitay** [comment]
https://laravel.com/docs/5.7/configuration#environment-configuration
https://pterodactyl.io/panel/configuration.html

It's already explained on the pterodactyl docs, env is a short name for environment.

**Comment by lancepioch** [comment]
This is already mentioned in the docs: https://pterodactyl.io/panel/getting_started.html#installation
