### ISSUE TITLE
Extra information regarding LXC

### ISSUE THREAD

**Issue by jjws600** [pterodactyl/documentation#439]
I noticed on this page [Wings- installing](https://pterodactyl.io/wings/1.0/installing.html) of the documentation, there is a section that says;

> To run Wings, you will need a Linux system capable of running Docker containers. Most VPS and almost all dedicated servers should be capable of running Docker, but there are edge cases.

> When your provider uses Virtuozzo, OpenVZ (or OVZ), or LXC virtualization, you will most likely be unable to run Wings. Some providers have made the necessary changes for nested virtualization to support Docker. Ask your provider's support team to make sure. KVM is guaranteed to work.

> The easiest way to check is to type systemd-detect-virt. If the result doesn't contain OpenVZ orLXC, it should be fine. The result of none will appear when running dedicated hardware without any virtualization.

This turned me away from using pterodactyl all together, for about a year, until I learned elsewhere that docker IS in fact compatible with LXC, IF you enable nesting. [and got the courage together to learn how to install pterodactyl which seems like a common problem among beginners looking for a panel as well]

My example is using Proxmox, where you can enable nesting via the features menu item, though I understand this is impossible for many using VPS, etc. but there could be a clarification to be added here that, you can use it you just have to ensure nesting is available.

This is my first issue, please let me know if I was correct in placing this here.

**Comment by Boy132** [comment]
> My example is using Proxmox, where you can enable nesting via the features menu item, though I understand this is impossible for many using VPS, etc. but there could be a clarification to be added here that, you can use it you just have to ensure nesting is available.

That's exactly what the docs say.

You even quoted it above:
>> When your provider uses [...] LXC virtualization, you will **most likely** be unable to run Wings. Some providers have made the necessary changes for **nested virtualization** to support Docker. Ask your provider's support team to make sure. KVM is guaranteed to work.

**Comment by jjws600** [comment]
I sure would love to learn to read... Thankyou. You saw nothing, end of issue. Lmao. Sorry for the waste of time.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
