### ISSUE TITLE
Update images on front page

### ISSUE THREAD

**Issue by AndyIsHereBoi** [pterodactyl/documentation#454]
Here I have a collection of images that will fit better on the front of the home page. (they are up to date)
I tried to put them in order of what people would want to see and the order they would visit them on the panel.

Admin node list:
![image](https://user-images.githubusercontent.com/69745145/172534542-ceb2b8da-3e7a-4040-860e-a03dade78e52.png)

Admin in node view:
![image](https://user-images.githubusercontent.com/69745145/172534195-6968604e-11d4-491c-adc2-21e6e8d7fe95.png)

Admin in server view:
![image](https://user-images.githubusercontent.com/69745145/172535321-71302b9d-12be-41c6-ba65-cc3d31e77dea.png)

Admin in startup view:
![image](https://user-images.githubusercontent.com/69745145/172535310-4e1e25fa-ef45-4f56-a748-b5b862492609.png)

Admin in eggs/scripts view:
![image](https://user-images.githubusercontent.com/69745145/172537412-76a0a1be-980b-4960-a5c9-3ae268b55837.png)

Client in server view:
![image](https://user-images.githubusercontent.com/69745145/172535994-efcc7235-8a4a-443a-a8ab-2f64e50e454d.png)

Client in file manager view:
![image](https://user-images.githubusercontent.com/69745145/172536133-8a5450e9-0594-4cf5-95ab-276f9e290283.png)

Client in file editor view:
![image](https://user-images.githubusercontent.com/69745145/172536215-b234a30c-b093-43ba-a362-01666ff572bd.png)

Client in backups view:
![image](https://user-images.githubusercontent.com/69745145/172536446-7f703435-914f-456a-a5a6-1c85091bb0b3.png)

Client in network view:
![image](https://user-images.githubusercontent.com/69745145/172537081-006d99ff-5611-4ffd-a73d-93b67458b7a3.png)

Client in API keys view:
![image](https://user-images.githubusercontent.com/69745145/172536912-410d369f-3629-4dfa-80af-e2efe4ae919a.png)

**Comment by Software-Noob** [comment]
Hi, please open a pull request should you wish to help update the images 👍
