### ISSUE TITLE
PHP Version Update

### ISSUE THREAD

**Issue by MorningSage** [pterodactyl/documentation#455]
Hi all,

Took me a bit to figure it out, but I believe the PHP version has changed since the Debian tutorial was created.

https://pterodactyl.io/community/installation-guides/panel/debian10.html

The tutorial states to install PHP 8.0 which results in a 502 Bad Gateway.  Installing PHP 8.1 fixes the issue and allows everything to work properly (at least thus far in my setup process, lol).

If this is something I did wrong, maybe we can outline whatever I did in the tutorial for others?  Otherwise, changing the version should be an easy fix.

Thanks for a great product!  I've had this running on another server for a long time and it works well.  Looking forward to using it on this one.

**Comment by Goksi** [comment]
You probably have 8.1 fpm socket inside of your webserver config, and as a result of that 8.0 will throw 502

**Comment by Software-Noob** [comment]
The community Debian guide installs PHP 8.0 and also specifies 8.0 PHP-fpm sock in the example web server config. Chances are, you didn't use the web server config from the Debian guide or overwrote it later when following the official panel installation guide 
written for Ubuntu which currently uses 8.1 in all examples.

Changing it to use 8.1 wouldn't be hard though, but community guides are not all kept up to date at all times right now and all could have some work done.

**Comment by MorningSage** [comment]
Ahh, the webserver config here:

https://pterodactyl.io/panel/1.0/webserver_configuration.html#nginx-without-ssl

This clearly outlines 8.1, yes.  I think I understand the issue now... Wouldn't we want both to match?

**Comment by Software-Noob** [comment]
The guide has been updated to also use 8.1 in #479
