### ISSUE TITLE
Add certbot -d example.com --manual --preferred-challenges dns certonly to Certbot Commands

### ISSUE THREAD

**Issue by rotvproHD** [pterodactyl/documentation#458]
`certbot -d example.com --manual --preferred-challenges dns certonly`

Is very useful when you for example want a Cert for a Node since else you would need to setup an nginx server on port 80 first and thats nnecessary, when you could just do this.

**Comment by Jelcoo** [comment]
There is no need for that since --standalone does what it says. It is a standalone that doesn't require nginx or apache2.

**Comment by Software-Noob** [comment]
`--standalone` spins up a temporary web server by certbot and doesn't require installing any yourself, but it still requires port 80 to be exposed for the HTTP challenge. DNS challenge can be useful to document since certbot DNS challenge is easier than acme for most users.
