### ISSUE TITLE
Changes for wings upgrade Documentation

### ISSUE THREAD

**Issue by GivouDev** [pterodactyl/documentation#460]
Hey,

for some distributions like Arch(which i use) you need for stop the wings service in order to override the execution file because curl doesn´t override busy files.

So it should be:

1. Stop Wings
2. Download new Wings Execution File
3. Set permissions
4. Start Wings

Wich makes also more sense to avoid errors that may occur while the service is still running

LG

**Comment by Software-Noob** [comment]
This has been added in 796913afb985e16cd515f412c063dfbc1f254b97
