### ISSUE TITLE
Add proxy documentation

### ISSUE THREAD

**Issue by TheRealGramdalf** [pterodactyl/documentation#476]
I wrote up some documentation on using a reverse proxy - is it possible to get this merged upstream? The fork is at https://github.com/TheRealGramdalf/documentation.

**Comment by TheRealGramdalf** [comment]
https://github.com/pterodactyl/documentation/pull/477

**Comment by Software-Noob** [comment]
There's no need to open an issue requesting to review a PR. It'll be reviewed once someone has time with feedback in the PR itself
