### ISSUE TITLE
Install doc specifically SSL and Certs

### ISSUE THREAD

**Issue by Talidorn** [pterodactyl/documentation#489]
I'm following the documentation on https://pterodactyl.io/community/installation-guides/panel/centos8.html.

I get to the point where you are to setup SSL.  It says follow the guide ->https://pterodactyl.io/tutorials/creating_ssl_certificates.html

That document says:

When you are using certbot's Nginx/Apache plugin, you won't need to restart your webserver to have the certificate applied assuming that you've already configured the webservers to use SSL as instructed in the [web server configuration step](https://pterodactyl.io/panel/1.0/webserver_configuration.html)

Ok, so now to the https://pterodactyl.io/panel/1.0/webserver_configuration.html document.

This one is where I got hung up.

It starts with (I'm guessing I need to do the steps for NGINX with SSL as that is the whole point right?

Issue 1 - First, remove the default NGINX configuration.  There is no such file, in AlmaLinux (guessing to follow CENTOS standards) in the directory listed.  Command suggested is rm /etc/nginx/sites-enabled/default.

Issue 2 - Create file /etc/nginx/conf.d/pterodactyl.conf (use the text in large box) and then sudo systemctl restart nginx.  Something somewhere has gone 100% wrong at this point.  nginix won't start now.  I think there is an selinux issue???? 

Yeah so I'm a bit stuck on install as the https/ssl thing is failing.

My workaround was to skip the SSL and just do NGINX with SSL.

**Comment by Software-Noob** [comment]
You can ignore sections not related to the guide you're following, as you only need the certificate. SSL certificate guide at this moment is a generic guide and mostly tailored towards Ubuntu, as that's what the official guide is using. The rest of the distro guides are under the community section and it's planned to merge everything properly at some point.

> Create file /etc/nginx/conf.d/pterodactyl.conf (use the text in large box) and then sudo systemctl restart nginx. Something somewhere has gone 100% wrong at this point. nginix won't start now. 

The service status would inform you what's wrong.

Please use the Discord server for support. Our support bot can reply to most issues, while the community might help with the rest.
