### ISSUE TITLE
composer.json file

### ISSUE THREAD

**Issue by vlotho** [pterodactyl/documentation#499]
Hello,

Following the copy of the .env environment file, the execution of composer by the command, "composer install --no-dev --optimize-autoloader", returns an error message asking for the creation of a "composer.json" file.

**Comment by danny6167** [comment]
The file exists, you're most likely in the wrong folder.
Please use the discord for support.

**Comment by vlotho** [comment]
If I got the directory wrong, I think it must be happening to someone else, so it would be useful to specify that in the documentation, I think.

**Comment by danny6167** [comment]
Basic Linux knowledge is expected.
The documentation already tells you what directory you need to be in and how to get there as one of the steps.
If people randomly decided to change directory for no reason that's not a matter for the documentation to fix.

**Comment by vlotho** [comment]
![Screenshot-1](https://user-images.githubusercontent.com/6847623/202846842-742e32ee-9f02-4977-bd7b-4eeb4da96c5e.png)
