### ISSUE TITLE
State of documentation

### ISSUE THREAD

**Issue by kylhuk** [pterodactyl/documentation#516]
was previously mentioned here: https://github.com/pterodactyl/panel/issues/4662

Pterodactyl just has too many undocumented values. There should be some effort to expose all possible configuration with a description and valid values.

I had two major issues while setting up Pterodactyl.

1) There is not mentioned that Pterodactyl is not working in a sub-path. When setting up a reverse proxy, this information is quite essential.
2) I had issues with CORS. I found two undocumented config settings, one in the Panel (`APP_CORS_ALLOWED_ORIGINS`) and one inside Wings (`allowed_origins`). The first one I only found because I was looking at the source code. The second one was mentioned in an issue over a year ago (https://github.com/pterodactyl/panel/issues/3599#issuecomment-912995176_). Ironically, @xorinzor also said this should be documented, but the issue was closed and forgotten.

So, can we please update the docs? This should be mainly done by those devs who implemented those config settings.

Thanks

--
kylhuk

**Comment by QuintenQVD0** [comment]
Most of the documentation is writing by the community in there free time. If you think something is missing the feel free to make a PR with what you think is needed to be added to the documentation

**Comment by FoksVHox** [comment]
I know that this already on the drawing board, Matthew has multiple times said in the Discord server, he intends to remake the docs, and include a first-party API docs. However, it won't be done, as the main priority is developing v2 of the panel, which I'd consider more important. 

As a sidenote, I have never had any issues with setting up the panel.

**Comment by tempusthales** [comment]
I don't think Matthew has a concept of time, he has said this documentation update was back in '22, and '23 and we are bout to hit 2024, and the documentation still sucks.

**Comment by kylhuk** [comment]
Closing this issue as this has been problem for years and the responsibility just gets pushed to the community, which has not written the code.
