### ISSUE TITLE
Enabling Webserver Configuration

### ISSUE THREAD

**Issue by kNoAPP** [pterodactyl/documentation#53]
On Ubuntu 18.04 Apache2 following the documentation's instructions to the dot, I ran into an error just after configuring the sites-available portion of Pterodactyl. More specifically...

`# You do not need to run any of these commands on CentOS`
`sudo ln -s /etc/apache2/sites-available/pterodactyl.conf /etc/apache2/sites-enabled/pterodactyl.conf`
`sudo a2enmod rewrite`
`systemctl restart apache2`

Here's the error:
[https://i.imgur.com/iFdn8eu.png](url)

To repair, I visited https://serverfault.com/questions/515417/error-start-apache-php-value and https://stackoverflow.com/questions/36057615/ubuntu-apache-module-php7-does-not-exist and found the following solution. Run the commands:

`sudo apt-get install libapache2-mod-php7.2`
`sudo a2enmod php7.2`
`sudo systemctl restart apache2`

Then I was able to continue following the guide without error.

**Comment by Sir3lit** [comment]
In the dependencies it does show you to install

`php7.2-fpm`
