### ISSUE TITLE
Nodesource repo deprecation warning

### ISSUE THREAD

**Issue by cmrxnn** [pterodactyl/documentation#543]
In the community guides (specifically 'Building panel assets'), there is a command to install NodeJS v16 in order to build the panel:
```
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
```

This script now throws a deprecation warning as follows:
![image](https://github.com/pterodactyl/documentation/assets/72230943/e0524aba-19b9-46d8-b80d-85a1bdb510d1)

Solution to this issue: Changing the method of installing NodeJS on the documentation so users don't use a deprecated (or, at some point, non-functional) install script for NodeJS

**Comment by Jcodeerd** [comment]
Will be fixed by https://github.com/pterodactyl/documentation/pull/542

**Comment by cmrxnn** [comment]
Probably should've checked the PR's before creating an issue...

I'll leave this here for tracking purposes and then it can either be closed now or when the PR is merged

**Comment by PadowYT2** [comment]
> Probably should've checked the PR's before creating an issue...
> 
> I'll leave this here for tracking purposes and then it can either be closed now or when the PR is merged

If the PR will be merged, GitHub will automatically close this issue. I have added this issue to the PR
