### ISSUE TITLE
Timzone error 

### ISSUE THREAD

**Issue by foxytouxxx** [pterodactyl/documentation#560]
Even when I change my vps timezone, it gives me this error : 
FATAL: [Oct 28 14:27:59.060] failed to detect system timezone or use supplied configuration value error-the supplied timezone /UTC is invalid: time: invalid
location name
Stacktrace:
time: invalid location name
the supplied timezone /UTC is invalid
github.com/pterodactyl/wings/cmd.rootCmdRun
github.com/pterodactyl/wings/cmd/root.go:106
github.com/spf13/cobra.(Command).execute
github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(Command).ExecuteC
github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
github.com/spf13/cobra@v1.7.0/command.go:992
github.com/pterodactyl/wings/cmd.Execute
github.com/pterodactyl/wings/cmd/root.go:71
main.main
github.com/pterodactyl/wings/wings.go:17
runtime.main
runtime/proc.go:250
runtime.goexit
runtime/asm_amd64.s:1598

**Comment by QuintenQVD0** [comment]
wy `/UTC` it should be just `UTC`
