### ISSUE TITLE
Installing Wings confusion

### ISSUE THREAD

**Issue by HunterZ** [pterodactyl/documentation#636]
I've been following the installation instructions for setting things up on an Ubuntu 24.04.1 LTS VM. Everything up through this point has been a bunch of command line stuff: https://pterodactyl.io/wings/1.0/installing.html#installing-wings-2

Suddenly this step says "create a node on your installed Panel" - but I have no idea what this means. Do I need to open a web browser and go to a URL or something? This isn't enough info, because I don't know what an "installed Panel" means: https://pterodactyl.io/wings/1.0/installing.html#configure

**Comment by yesBad** [comment]
"Installed Panel" is the panel you've installed before installing Wings.
Here is the documentation for it: <https://pterodactyl.io/panel/1.0/getting_started.html>


So it works by having a singular "panel" aka website that manages all of the multiple wings instances you may have.

**Comment by HunterZ** [comment]
Note that the documentation here also doesn't mention the location setup at all.

**Comment by danny6167** [comment]
Between the phrases "Installed Panel" and "Go to your Panel administrative view", plus the screenshot right below that, it's pretty clear where you need to go.

As far as I remember, the panel also tells you that you need to create a location if you don't have one.
