### ISSUE TITLE
.env file is not being generated

### ISSUE THREAD

**Issue by gstokebrand** [pterodactyl/documentation#89]
My .env file is not being generated after i type:
`cp .env.example .env`
Then when i type:
`composer install --no-dev --optimize-autoloader`
everything seems fine but when i type:
`php artisan key:generate --force`
No key shows up. it just says:

> Application key set succesfully.

but no key is given and there also is not an .env file in /var/www/pterodactyl
Iam on Debian 9

**Comment by DaneEveritt** [comment]
Please follow the template in the issue if you want your issue to remain open. However this doesn't appear to be a bug, please use Discord for further assistance.

**Comment by UltronReal** [comment]
The file is already there, only it was hidden
Use: nano /var/www/pterodactyl/.env
